name: CI/macOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: [macos-10.15]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: mkdir -p ${{runner.workspace}}/build

    - name: Cache CPAN Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ${{runner.workspace}}/local
        key: cpan-${{ runner.os }}-${{ hashFiles('cpanfile') }}

    - name: Install Dependencies
      run: |
        brew install expect nghttp2 cpm ruby bison

    - name: Install cURL
      run: |
        set -x
        # install curl 7.57.0 because t/50fastcgi.t depends on it.
        wget --no-verbose -O - https://curl.haxx.se/download/curl-7.57.0.tar.gz | tar xzf -
        cd curl-7.57.0
        ./configure --prefix=$HOME --with-darwinssl --without-brotli --with-nghttp2 --disable-shared --disable-manual
        make
        make install
        $HOME/bin/curl --version

    - name: Install CPAN Dependencies
      run: |
        perl -V
        cpm install --with-recommends --show-build-log-on-failure -L "${{runner.workspace}}/local"

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -B.

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: make all

    - name: Build CheckDepends
      working-directory: ${{runner.workspace}}/build
      run: make checkdepends

    - name: Test
      timeout-minutes: 90
      working-directory: ${{runner.workspace}}/build
      env:
        PERL5OPT: "-Mlib=${{runner.workspace}}/local/lib/perl5"
      run: |
        set -x
        # look up $HOME/bin first for the custom curl
        export PATH="$HOME/bin:$PATH"
        echo $PATH
        make check VERBOSE=1
